// api/_lib/facebookTranscript.js
// Lấy transcript/phụ đề video Facebook — song song với youtubeTranscript.js
// nhưng cho Facebook. Dùng resolveFacebookVideo() (api/_lib/facebookVideo.js)
// để trích captions_url nhúng sẵn trong trang xem video.
//
// GIỚI HẠN: khác YouTube (hầu hết video giáo dục public đều có phụ đề tự
// động), Facebook CHỈ có captions_url khi chủ video chủ động bật phụ đề —
// tỉ lệ thấp hơn nhiều. Video không có sẽ báo lỗi rõ ràng ngay (thay vì âm
// thầm trả kết quả sai) để phía gọi (videoToLearningProxy.js) tự động
// fallback sang Gemini xem thẳng video (dùng directUrl trích được).

import { resolveFacebookVideo, FacebookVideoError } from './facebookVideo.js'

export class FacebookTranscriptError extends Error {
  constructor(message, status = 502) {
    super(message)
    this.name = 'FacebookTranscriptError'
    this.status = status
  }
}

const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36'

const MAX_TRANSCRIPT_CHARS = 24000 // tránh vượt context/token limit của Groq, đồng bộ youtubeTranscript.js

// Phụ đề Facebook thường ở định dạng WebVTT (.vtt) — parse thô: bỏ header
// "WEBVTT", timestamp, số thứ tự cue, chỉ giữ lại phần text rồi ghép câu.
function parseVtt(vttText) {
  const lines = vttText.split(/\r?\n/)
  const textLines = []
  for (const line of lines) {
    const trimmed = line.trim()
    if (!trimmed) continue
    if (trimmed === 'WEBVTT') continue
    if (/^\d+$/.test(trimmed)) continue // số thứ tự cue
    if (/-->/.test(trimmed)) continue // dòng timestamp
    // Bỏ thẻ kiểu <c>, <00:00:01.000> nếu có
    const clean = trimmed.replace(/<[^>]*>/g, '').trim()
    if (clean) textLines.push(clean)
  }
  return textLines.join(' ').replace(/\s+/g, ' ').trim()
}

export async function fetchFacebookTranscript(videoUrl) {
  let resolved
  try {
    resolved = await resolveFacebookVideo(videoUrl)
  } catch (err) {
    if (err instanceof FacebookVideoError) {
      throw new FacebookTranscriptError(err.message, err.status)
    }
    throw new FacebookTranscriptError('Không đọc được trang video Facebook.', 502)
  }

  if (!resolved.captionsUrl) {
    throw new FacebookTranscriptError(
      'Video Facebook này không có phụ đề (caption) nên không thể phân tích miễn phí bằng transcript. Hãy thử một video khác có bật phụ đề, hoặc hệ thống sẽ tự chuyển sang xem trực tiếp video (Gemini).',
      422,
    )
  }

  const captionsRes = await fetch(resolved.captionsUrl, { headers: { 'User-Agent': UA } })
  if (!captionsRes.ok) {
    throw new FacebookTranscriptError('Không tải được nội dung phụ đề Facebook.', 502)
  }
  const vttText = await captionsRes.text()
  const transcript = parseVtt(vttText)

  if (!transcript) {
    throw new FacebookTranscriptError('Phụ đề video Facebook này trống, không thể phân tích.', 422)
  }

  const truncated =
    transcript.length > MAX_TRANSCRIPT_CHARS ? transcript.slice(0, MAX_TRANSCRIPT_CHARS) + ' […]' : transcript

  return {
    transcript: truncated,
    languageCode: 'unknown',
    isAutoGenerated: false,
    directUrl: resolved.directUrl,
    title: resolved.title,
  }
}
