import React, { createContext, useContext, useState, useEffect } from 'react'

const AppContext = createContext(null)

export const TRANSLATIONS = {
  vi: {
    appName: 'Consensus Doctor',
    tagline: 'Nền tảng AI Y tế · Digital Twin Bệnh nhân',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    logout: 'Đăng xuất',
    email: 'Email',
    password: 'Mật khẩu',
    name: 'Họ và tên',
    continueGoogle: 'Tiếp tục với Google',
    continueApple: 'Tiếp tục với Apple',
    orEmail: 'Hoặc dùng email',
    noAccount: 'Chưa có tài khoản?',
    hasAccount: 'Đã có tài khoản?',
    welcome: 'Xin chào',
    dashboard: 'Tổng quan',
    patients: 'Siêu Anh Hùng',
    imaging: 'Chẩn đoán hình ảnh',
    checkin: 'Kiểm tra triệu chứng',
    matrix3dBody: 'Matrix-3D Body',
    omnidirectional3dBody: 'Omnidirectional Explorable 3D Body Generation',
    twin: 'Digital Twin',
    telemedicine: 'Telemedicine',
    statAnalysis: 'AI Agent phân tích thống kê',
    simulation: 'Mô phỏng điều trị',
    consensus: 'Đồng thuận AI',
    protein3d: 'Protein 3D',
    swarmCouncil: '🏛 Hội đồng AI',
    adminPanel: 'Quản trị hệ thống',
    familyTree: 'Gia phả bệnh lý',
    familyRelationship: 'Family Medical Relationship',
    familyRelationshipMap: 'Family Relationship Map',
    familyRelationshipInference: 'Family Relationship Inference',
    uploadRecords: 'Tải lên hồ sơ',
    healthJourney: 'Buổi Sáng',
    lunchJourney: 'buổi trưa',
    dinnerJourney: 'buổi tối',
    aiHealthcareVision: 'AI Healthcare Vision',
    aiHealthcareVisionControl: 'AI Healthcare Vision Control',
    visionSync: 'Vision Sync',
    videoAnalyzer: 'Phân Tích Video',
    remixSucKhoeKOL: 'Remix Sức Khoẻ từ KOL',
    vibeTracking: 'Vibe Tracking',
    vibeCheck: 'Vibe Check',
    videoToLearning: 'Video to Learning',
    bringAnyIdeaToLife: 'Bring Any Idea to Life',
    stressRelief: 'Góc xả stress',
    xyzCameraAngle: 'Góc chụp toạ độ XYZ',
    aiInbodyPortal: 'AI inbody Portal',
    waterDrinkChatBot: 'Bé Mèo Nước',
    wikiMedVision: 'Wiki Med Vision',
    patientRecord: 'Hồ sơ Siêu Anh Hùng / Hero Record',
    addPatient: 'Thêm Siêu Anh Hùng / Add Hero',
    allPatients: 'Tất cả Siêu Anh Hùng / All Heroes',
    medicalHistory: 'Lịch sử bệnh án',
    recommendations: 'Gợi ý xét nghiệm',
    darkMode: 'Chế độ tối',
    lightMode: 'Chế độ sáng',
    language: 'Ngôn ngữ',
    profile: 'Hồ sơ cá nhân',
    nav_aiChatbotControl: 'AI chatbot control',
    aiChatbotControlSubtitle: 'Trò chuyện thoại với AI companion — miễn phí, dùng giọng nói trình duyệt (khuyên dùng Chrome) + API Gemini sẵn có. Tự chỉnh giọng nói, tính cách, màu sắc nhân vật.',
    aiChatbotControlMissingKey: 'Chưa cấu hình khoá API. Vui lòng thêm biến môi trường sau vào file .env rồi khởi động lại app:',
    agentsActive: 'AGENT ĐANG HOẠT ĐỘNG',
    next: 'Tiếp theo',
    back: 'Quay lại',
    save: 'Lưu',
    cancel: 'Hủy',
    upload: 'Tải lên',
    uploadFile: 'Chọn hoặc kéo thả file',
    uploadTypes: 'Hỗ trợ: DICOM, PDF, JPEG, PNG, DOCX',
    familyRelation: 'Quan hệ',
    addFamilyMember: 'Thêm thành viên',
    aiSuggestion: 'Gợi ý AI',
    testSuggestion: 'Xét nghiệm được gợi ý',
    confidence: 'Độ tin cậy',
    allUsers: 'Tất cả người dùng',
    allRecords: 'Tất cả hồ sơ',
    activityLog: 'Nhật ký hoạt động',
    adminOnly: 'Chỉ dành cho quản trị viên',
    loginRequired: 'Vui lòng đăng nhập để tiếp tục',
    patientProgress: 'Tiến triển bệnh',
    uploadSuccess: 'Tải lên thành công',
    relation_self: 'Siêu Anh Hùng',
    relation_father: 'Cha',
    relation_mother: 'Mẹ',
    relation_sibling: 'Anh/Chị/Em',
    relation_child: 'Con',
    relation_spouse: 'Vợ/Chồng',
    relation_grandparent: 'Ông/Bà',
    relation_grandchild: 'Cháu',
    relation_uncle_aunt: 'Chú/Cô',
    relation_cousin: 'Anh em họ',
    // Sidebar navigation
    nav_zeroToForever: 'Zero to Forever - Trang chủ',
    nav_chooseUserRole: 'Chọn Vai Trò Anh Hùng',
    nav_donationHero: 'Anh Hùng Hiến Tặng',
    nav_affiliateUuidReferral: 'Đăng Ký Affiliate Marketing',
    nav_avatarCreator: 'Tạo Avatar',
    nav_comicHeroGame: 'Tạo Game bằng Avatar của Tôi',
    nav_comicIssueLibrary: 'Thư Viện Truyện Của Tôi',
    nav_petPassportAdventure: 'Pet Passport Adventure',
    nav_bodyProtectionJourney: 'Hành Trình Bảo Vệ Cơ Thể',
    nav_affiliateGame: '🎁 Affiliate Game',
    nav_hero3DMap: 'Bản Đồ 3D Cho Anh Hùng',
    nav_myPainPathBody: 'Đường Đau Của Tôi - Cơ Thể',
    nav_myPainPathBodyPixel: 'Đường Đau Của Tôi - Cơ Thể Pixel',
    nav_myPainPathNoiTang: 'Đường Đau Của Tôi - Nội Tạng',
    nav_myPainPathNoiTangPixel: 'Đường Đau Của Tôi - Nội Tạng Pixel',
    nav_healthJourneyGame: 'Trò Chơi Hành Trình Sức Khỏe',
    nav_medicalAssetStore: 'Chợ Tài Nguyên 3D',
    nav_medicalVisualPlayground: 'Phòng Lab Y Tế 3D (Không Chạm)',
    nav_medicalVisualCameraAngle3D: 'Góc Camera Y Tế 3D',
    nav_myRewardHealth: 'Phần Thưởng Sức Khỏe Của Tôi',
    nav_affiliate: 'Affiliate & Kiếm Tiền Đa Tầng',
    nav_rssPortal: 'Cổng RSS Sức Khỏe',
    nav_fullDocSummarization: 'Tóm Tắt Toàn Văn Tài Liệu',
    nav_documentOCR: 'Nhận Diện Văn Bản (OCR)',
    nav_cameraAngle3DStudio: 'Studio Góc Camera 3D',
    nav_organConnection: 'Ăn Gì Tốt Hôm Nay',
    nav_heirloomRecipes: 'Bữa ăn heirloom recipes',
    nav_cookingGuide: 'Hướng Dẫn Nấu Ăn Ngon Và Khỏe Mạnh',
    nav_varCheck: 'VAR Y Tế',
    nav_printPortal: 'Cổng In Ấn',
    nav_patientReflect: 'Phản Chiếu Siêu Anh Hùng',
    nav_chatHistory: 'Lịch Sử Chat Với AI',
    admin_make3DModel: 'Tạo Mô Hình 3D',
    admin_my3dAsset: 'Tài Nguyên 3D Của Tôi',
    admin_twoDTo3DAsset: '2D Sang Tài Nguyên 3D',
    admin_videoToLearningAdmin: 'Quản Trị Video to Learning',
    admin_affiliateAdmin: 'Quản Trị Affiliate',
    admin_roleMembershipAdmin: 'Quản Trị Vai Trò & Nâng Cấp Thành Viên',
    admin_moralisPlaygroundAdmin: 'Moralis Playground Admin',
    admin_affiliateWebhookAdmin: 'Quản Trị Affiliate Webhook',
    admin_create3DVideoFrom2D: 'Tạo Video 3D Từ 2D',
    admin_adminConcept: 'Bảng Quản Trị AI Doctor',
    sim_affiliateControl: 'Bảng Điều Khiển Affiliate (Mô Phỏng)',
    section_vipProOnly: 'Chỉ Dành Cho Tài Khoản VIP PRO',
    section_admin: 'Quản Trị',
    section_simulationInternal: 'Mô Phỏng (Nội Bộ)',
    section_aiAgents: 'AI Agents',
    section_patientsJourney: 'Hành Trình Siêu Anh Hùng',
    // Checkin
    checkinTitle: 'Kiểm tra triệu chứng & Tiền sử',
    seedCollection: 'THU THẬP DỮ LIỆU',
    personalHistory: 'Tiền sử cá nhân',
    familyHistory: 'Tiền sử gia đình',
    currentSymptoms: 'Triệu chứng hiện tại',
    envSignals: 'Tín hiệu môi trường',
    buildTwin: 'Xây dựng Digital Twin →',
    // Imaging
    imagingTitle: 'Phân tích hình ảnh y tế',
    lesionTracking: 'Theo dõi tổn thương',
    aiFinding: 'Phát hiện AI',
    scanTimeline: 'Lịch sử chụp',
    continueCheckin: 'Tiếp tục kiểm tra triệu chứng →',
    // Twin
    twinTitle: 'Digital Twin Y tế',
    twinActive: 'TWIN ĐANG HOẠT ĐỘNG',
    activeAgents: 'Agent đang hoạt động',
    twinFidelity: 'Độ chính xác twin',
    interactionsPerSec: 'Tương tác / giây',
    realityMatch: 'Điểm khớp thực tế',
    bodyComposition: 'Chỉ số cơ thể',
    runSimulation: 'Chạy mô phỏng điều trị →',
    // Telemedicine
    telemedicineTitle: 'Telemedicine · Livestream hội chẩn',
    telemedicineSubtitle: 'Livestream đồng thời 3 bác sĩ vật lý thật và 5 bác sĩ AI agent. Bác sĩ hoặc agent nào không có tín hiệu sẽ tự động hiển thị chế độ OFFLINE.',
    aiAgentRoom: 'Phòng bác sĩ AI agent',
    aiAgentRoomHint: '4 agent online · 1 agent offline standby',
    handoffTitle: 'Luồng hội chẩn song song',
    handoffCopy: 'Video từ bác sĩ thật được ghép với phân tích của AI agent theo thời gian thực, giúp hội đồng Digital Twin chuyển ca sang đồng thuận AI khi đủ dữ liệu.',
    continueAiCouncil: 'Tiếp tục tới Hội đồng AI →',
    // Statistical analysis
    statAnalysisTitle: 'AI Agent phân tích thống kê HPV',
    statAnalysisSubtitle: 'Agent đọc dữ liệu từ bài báo Long Châu, chuẩn hoá các con số thực tế và tạo biểu đồ scatter HTML tương tác với trục Y là tín hiệu HPV (0–100).',
    statFiltersTitle: '4 bộ lọc khám phá',
    statFiltersHint: 'Chọn từng lớp dữ liệu để xem cụm tuổi và tín hiệu HPV mô phỏng.',
    statOutcomeTitle: 'OUTPUT / OUTCOME',
    statOutcomeCopy: 'Biểu đồ mới chuyển ngữ cảnh từ liều thuốc sang tín hiệu HPV, giúp nhận diện nhóm cần tầm soát, chủng nguy cơ cao và tác động của vắc xin.',
    // Simulation
    simulationTitle: 'Mô phỏng điều trị',
    simulationMode: 'CHẾ ĐỘ MÔ PHỎNG',
    selectScenario: 'Chọn kịch bản điều trị',
    projectionHorizon: 'Khoảng chiếu',
    treatmentRoadmap: 'Lộ trình điều trị',
    submitConsensus: 'Gửi tới Đồng thuận AI →',
    // Consensus
    consensusTitle: 'Đồng thuận Agent',
    consensusReached: 'ĐÃ ĐẠT ĐỒNG THUẬN',
    fusionMethod: 'Phương pháp tổng hợp',
    runConsensus: 'Chạy đồng thuận agent',
    newScan: '← Quét mới',
    rerunConsensus: '↺ Chạy lại đồng thuận',
    compareAllMethods: 'So sánh 4 phương pháp tổng hợp',
    // Upload
    uploading: 'Đang tải lên...',
    notes: 'Ghi chú',
    notesPlaceholder: 'Ghi chú (tuỳ chọn)...',
    recordsUploaded: 'hồ sơ đã tải',
    uploadPatientName: 'Siêu Anh Hùng Upload / Upload Hero',
    pendingAnalysis: 'Đang chờ phân tích',
    uploadedSummary: 'Tổng cộng {count} hồ sơ được tải lên',
    uploadedTimelineEvent: 'Upload {type}: {label}',
    noUploadPatientName: 'Chưa có hồ sơ upload',
    noUploadPatientDisease: 'Upload hồ sơ để tạo bệnh án cá nhân',
    uploadDataBanner: 'Dữ liệu từ Hồ Sơ Upload',
    uploadDataStats: '{files} file · {images} ảnh có AI phân tích',
    backToDemo: '← Back to Hero / Siêu Anh Hùng',
    backToMyRecords: '← Hồ sơ của tôi',
    backToDemoRecord: '← Back to Hero / Siêu Anh Hùng',
    // Admin
    totalUsers: 'Tổng người dùng',
    medicalRecords: 'Hồ sơ y tế',
    analysesToday: 'Phân tích hôm nay',
    activePatients: 'Siêu Anh Hùng đang theo dõi / Active Heroes',
    session: 'Phiên làm việc',
    accounts: 'tài khoản',
    records: 'hồ sơ',
    noUsers: 'Chưa có người dùng nào ngoài admin',
    noRecords: 'Chưa có hồ sơ nào được tải lên',
    // Family
    familyTreeTitle: 'Gia phả bệnh lý',
    familyRelationshipTitle: 'Family Medical Relationship',
    membersCount: 'thành viên',
    aiHereditary: 'Phân tích nguy cơ di truyền AI',
    memberList: 'Danh sách thành viên',
    addMember: 'Thêm thành viên',
    confirmDelete: 'Xác nhận xoá?',
    screeningRec: 'Khuyến nghị tầm soát',
    riskHigh: 'Nguy cơ cao',
    riskMedium: 'Nguy cơ trung bình',
    riskLow: 'Nguy cơ thấp',
    fromFamily: 'Từ Gia phả',
    viewingMember: 'Đang xem hồ sơ thành viên gia đình',
    backToMain: '← Quay lại Lê Xuân Khánh',
    // Profile modal
    welcomeTitle: 'Chào mừng đến Consensus Doctor!',
    profileCreated: 'Hồ sơ đã được tạo từ tài khoản của bạn. Xem lại và chỉnh sửa nếu cần.',
    specialtyRole: 'Chuyên khoa / Vai trò',
    optional: 'tùy chọn',
    phone: 'Số điện thoại',
    editAnytime: 'Bạn có thể chỉnh sửa thông tin này bất cứ lúc nào trong phần Hồ sơ cá nhân.',
    skip: 'Bỏ qua',
    saveProfile: '💾 Lưu hồ sơ',
    adminLoginGoogle: 'Đăng nhập Admin (Google)',
    autoAvatar: '· Avatar tự động',
  },
  en: {
    appName: 'Consensus Doctor',
    tagline: 'Medical AI Platform · Patient Digital Twin',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    continueGoogle: 'Continue with Google',
    continueApple: 'Continue with Apple',
    orEmail: 'Or use email',
    noAccount: "Don't have an account?",
    hasAccount: 'Already have an account?',
    welcome: 'Welcome',
    dashboard: 'Dashboard',
    patients: 'Heroes / Siêu Anh Hùng',
    imaging: 'Imaging Analysis',
    checkin: 'Symptom Check-in',
    matrix3dBody: 'Matrix-3D Body',
    omnidirectional3dBody: 'Omnidirectional Explorable 3D Body Generation',
    twin: 'Digital Twin',
    telemedicine: 'Telemedicine',
    statAnalysis: 'AI Agent Stats',
    simulation: 'Treatment Simulation',
    consensus: 'AI Consensus',
    protein3d: 'Protein 3D',
    swarmCouncil: '🏛 AI Board',
    adminPanel: 'Admin Panel',
    familyTree: 'Family Medical Tree',
    familyRelationship: 'Family Medical Relationship',
    familyRelationshipMap: 'Family Relationship Map',
    familyRelationshipInference: 'Family Relationship Inference',
    uploadRecords: 'Upload Records',
    healthJourney: 'Morning',
    lunchJourney: 'Noon',
    dinnerJourney: 'Evening',
    aiHealthcareVision: 'AI Healthcare Vision',
    aiHealthcareVisionControl: 'AI Healthcare Vision Control',
    visionSync: 'Vision Sync',
    videoAnalyzer: 'Video Analyzer',
    remixSucKhoeKOL: 'Health Remix from KOLs',
    vibeTracking: 'Vibe Tracking',
    vibeCheck: 'Vibe Check',
    videoToLearning: 'Video to Learning',
    bringAnyIdeaToLife: 'Bring Any Idea to Life',
    stressRelief: 'Stress Relief Corner',
    xyzCameraAngle: 'XYZ Camera Angle Corner',
    aiInbodyPortal: 'AI inbody Portal',
    waterDrinkChatBot: 'Bé Mèo Nước',
    wikiMedVision: 'Wiki Med Vision',
    patientRecord: 'Hero Record / Hồ sơ Siêu Anh Hùng',
    addPatient: 'Add Hero / Thêm Siêu Anh Hùng',
    allPatients: 'All Heroes / Tất cả Siêu Anh Hùng',
    medicalHistory: 'Medical History',
    recommendations: 'Test Recommendations',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    language: 'Language',
    profile: 'Profile',
    nav_aiChatbotControl: 'AI chatbot control',
    aiChatbotControlSubtitle: 'Voice chat with an AI companion — free, using your browser\'s speech engine (Chrome recommended) + the existing Gemini API. Customize its voice, personality, and color.',
    aiChatbotControlMissingKey: 'API key not configured. Please add the following environment variable to your .env file and restart the app:',
    agentsActive: 'AGENTS ACTIVE',
    next: 'Next',
    back: 'Back',
    save: 'Save',
    cancel: 'Cancel',
    upload: 'Upload',
    uploadFile: 'Select or drag & drop file',
    uploadTypes: 'Supported: DICOM, PDF, JPEG, PNG, DOCX',
    familyRelation: 'Relation',
    addFamilyMember: 'Add Member',
    aiSuggestion: 'AI Suggestion',
    testSuggestion: 'Suggested Tests',
    confidence: 'Confidence',
    allUsers: 'All Users',
    allRecords: 'All Records',
    activityLog: 'Activity Log',
    adminOnly: 'Admin Access Only',
    loginRequired: 'Please login to continue',
    patientProgress: 'Disease Progress',
    uploadSuccess: 'Upload Successful',
    relation_self: 'Hero / Siêu Anh Hùng',
    relation_father: 'Father',
    relation_mother: 'Mother',
    relation_sibling: 'Sibling',
    relation_child: 'Child',
    relation_spouse: 'Spouse',
    relation_grandparent: 'Grandparent',
    relation_grandchild: 'Grandchild',
    relation_uncle_aunt: 'Uncle/Aunt',
    relation_cousin: 'Cousin',
    // Sidebar navigation
    nav_zeroToForever: 'Zero to Forever - Home',
    nav_chooseUserRole: 'Choose Hero Role',
    nav_donationHero: 'Donor Hero',
    nav_affiliateUuidReferral: 'Affiliate Marketing Signup',
    nav_avatarCreator: 'Create Avatar',
    nav_comicHeroGame: 'Build a Game with My Avatar',
    nav_comicIssueLibrary: 'My Comic Library',
    nav_petPassportAdventure: 'Pet Passport Adventure',
    nav_bodyProtectionJourney: 'Body Protection Journey',
    nav_affiliateGame: '🎁 Affiliate Game',
    nav_hero3DMap: '3D Map for Hero',
    nav_myPainPathBody: 'My Pain Path Body',
    nav_myPainPathBodyPixel: 'My Pain Path Body Pixel',
    nav_myPainPathNoiTang: 'My Pain Path Internal Organs',
    nav_myPainPathNoiTangPixel: 'My Pain Path Internal Organs Pixel',
    nav_healthJourneyGame: 'Health Journey Game',
    nav_medicalAssetStore: '3D Asset Store',
    nav_medicalVisualPlayground: 'Medical 3D Lab (Touchless)',
    nav_medicalVisualCameraAngle3D: 'Medical Camera Angle 3D',
    nav_myRewardHealth: 'My Reward Health',
    nav_affiliate: 'Affiliate & Multi-tier Earn',
    nav_rssPortal: 'Healthy RSS Portal',
    nav_fullDocSummarization: 'Full-Document Summarization',
    nav_documentOCR: 'Document OCR',
    nav_cameraAngle3DStudio: '3D Camera Angle Studio',
    nav_organConnection: 'What to Eat Today',
    nav_heirloomRecipes: 'Heirloom Recipes Meal Book',
    nav_cookingGuide: 'Cooking Guide: Delicious & Healthy',
    nav_varCheck: 'Medical VAR',
    nav_printPortal: 'Print Portal',
    nav_patientReflect: 'Hero Reflection',
    nav_chatHistory: 'AI Chat History',
    admin_make3DModel: 'Make 3D Model',
    admin_my3dAsset: 'My 3D Asset',
    admin_twoDTo3DAsset: '2D to 3D Asset',
    admin_videoToLearningAdmin: 'Video to Learning Admin',
    admin_affiliateAdmin: 'Affiliate Admin',
    admin_roleMembershipAdmin: 'Role & Membership Upgrade Admin',
    admin_moralisPlaygroundAdmin: 'Moralis Playground Admin',
    admin_affiliateWebhookAdmin: 'Affiliate Webhook Admin',
    admin_create3DVideoFrom2D: 'Create 3D Video From 2D',
    admin_adminConcept: 'AI Doctor Admin Panel',
    sim_affiliateControl: 'Affiliate Control Panel (Simulation)',
    section_vipProOnly: 'VIP PRO Accounts Only',
    section_admin: 'Admin',
    section_simulationInternal: 'Simulation (Internal)',
    section_aiAgents: 'AI Agents',
    section_patientsJourney: 'Hero Journey',
    // Checkin
    checkinTitle: 'Symptom & History Check-in',
    seedCollection: 'SEED COLLECTION',
    personalHistory: 'Personal History',
    familyHistory: 'Family Medical History',
    currentSymptoms: 'Current Symptoms',
    envSignals: 'Environmental Seed Signals',
    buildTwin: 'Build Digital Twin →',
    // Imaging
    imagingTitle: 'Medical Imaging Analysis',
    lesionTracking: 'Lesion Tracking',
    aiFinding: 'AI Finding',
    scanTimeline: 'Scan Timeline',
    continueCheckin: 'Continue to Symptom Check-in →',
    // Twin
    twinTitle: 'Medical Digital Twin',
    twinActive: 'TWIN ACTIVE',
    activeAgents: 'Active agents',
    twinFidelity: 'Twin fidelity',
    interactionsPerSec: 'Interactions / sec',
    realityMatch: 'Reality match score',
    bodyComposition: 'Body Composition Index',
    runSimulation: 'Run Treatment Simulations →',
    // Telemedicine
    telemedicineTitle: 'Telemedicine · Live consultation',
    telemedicineSubtitle: 'A simultaneous livestream with 3 real physical doctors and 5 AI doctor agents. Any doctor or agent without signal is automatically shown in OFFLINE mode.',
    aiAgentRoom: 'AI doctor agent room',
    aiAgentRoomHint: '4 agents online · 1 agent offline standby',
    handoffTitle: 'Parallel consultation flow',
    handoffCopy: 'Real-doctor video is paired with real-time AI agent reasoning so the Digital Twin council can hand off to AI consensus when enough context is available.',
    continueAiCouncil: 'Continue to AI Board →',
    // Statistical analysis
    statAnalysisTitle: 'AI Agent HPV statistical analysis',
    statAnalysisSubtitle: 'The agent reads Long Châu article signals, normalizes the real-world figures, and renders an interactive HTML scatter chart with the Y-axis as HPV signal (0–100).',
    statFiltersTitle: '4 exploration filters',
    statFiltersHint: 'Select each data layer to inspect age clusters and simulated HPV signal.',
    statOutcomeTitle: 'OUTPUT / OUTCOME',
    statOutcomeCopy: 'The new chart shifts the context from dosage to HPV signal, making screening gaps, high-risk strains, and vaccination impact easier to see.',
    // Simulation
    simulationTitle: 'Treatment Simulation',
    simulationMode: 'SIMULATION MODE',
    selectScenario: 'Select Treatment Scenario',
    projectionHorizon: 'Projection horizon',
    treatmentRoadmap: 'Treatment Roadmap',
    submitConsensus: 'Submit to Agent Consensus →',
    // Consensus
    consensusTitle: 'Agent Consensus',
    consensusReached: 'CONSENSUS REACHED',
    fusionMethod: 'Fusion method',
    runConsensus: 'Run Agent Consensus',
    newScan: '← New Scan',
    rerunConsensus: '↺ Re-run Consensus',
    compareAllMethods: 'Compare all 4 fusion methods',
    // Upload
    uploading: 'Uploading...',
    notes: 'Notes',
    notesPlaceholder: 'Notes (optional)...',
    recordsUploaded: 'records uploaded',
    uploadPatientName: 'Upload Hero / Siêu Anh Hùng Upload',
    pendingAnalysis: 'Pending analysis',
    uploadedSummary: '{count} records uploaded in total',
    uploadedTimelineEvent: 'Uploaded {type}: {label}',
    noUploadPatientName: 'No uploaded records yet',
    noUploadPatientDisease: 'Upload records to create your personal medical chart',
    uploadDataBanner: 'Data from Uploaded Records',
    uploadDataStats: '{files} file(s) · {images} AI-analyzed image(s)',
    backToDemo: '← Back to Hero / Siêu Anh Hùng',
    backToMyRecords: '← My records',
    backToDemoRecord: '← Back to Hero / Siêu Anh Hùng',
    // Admin
    totalUsers: 'Total Users',
    medicalRecords: 'Medical Records',
    analysesToday: 'Analyses Today',
    activePatients: 'Active Heroes / Siêu Anh Hùng đang theo dõi',
    session: 'Session',
    accounts: 'accounts',
    records: 'records',
    noUsers: 'No users yet except admin',
    noRecords: 'No records uploaded yet',
    // Family
    familyTreeTitle: 'Family Disease Tree',
    familyRelationshipTitle: 'Family Medical Relationship',
    membersCount: 'members',
    aiHereditary: 'AI Hereditary Risk Analysis',
    memberList: 'Member List',
    addMember: 'Add Member',
    confirmDelete: 'Confirm Delete?',
    screeningRec: 'Screening Recommendations',
    riskHigh: 'High Risk',
    riskMedium: 'Medium Risk',
    riskLow: 'Low Risk',
    fromFamily: 'From Family Tree',
    viewingMember: 'Viewing family member record',
    backToMain: '← Back to Lê Xuân Khánh',
    // Profile modal
    welcomeTitle: 'Welcome to Consensus Doctor!',
    profileCreated: 'Your profile was created from your account. Review and update if needed.',
    specialtyRole: 'Specialty / Role',
    optional: 'optional',
    phone: 'Phone',
    editAnytime: 'You can edit this information anytime in your Profile settings.',
    skip: 'Skip',
    saveProfile: '💾 Save profile',
    adminLoginGoogle: 'Admin login (Google)',
    autoAvatar: '· Auto avatar',
  }
}

const HERO_THEME_KEY = 'heroPanel:theme'
const HERO_LANG_KEY = 'heroPanel:lang'
const HERO_PREFS_EVENT = 'heroPanelPrefsChange'

const readStoredTheme = () => {
  const stored = localStorage.getItem('cdoc_theme') || localStorage.getItem(HERO_THEME_KEY)
  return stored === 'light' ? 'light' : 'dark'
}

const readStoredLang = () => {
  const stored = localStorage.getItem('cdoc_lang') || localStorage.getItem(HERO_LANG_KEY)
  return stored === 'en' ? 'en' : 'vi'
}

export function AppProvider({ children }) {
  const [theme, setTheme] = useState(readStoredTheme)
  const [lang, setLang] = useState(readStoredLang)

  useEffect(() => {
    localStorage.setItem('cdoc_theme', theme)
    localStorage.setItem(HERO_THEME_KEY, theme)
    document.documentElement.setAttribute('data-theme', theme)
    window.dispatchEvent(new Event(HERO_PREFS_EVENT))
  }, [theme])

  useEffect(() => {
    localStorage.setItem('cdoc_lang', lang)
    localStorage.setItem(HERO_LANG_KEY, lang)
    window.dispatchEvent(new Event(HERO_PREFS_EVENT))
  }, [lang])

  useEffect(() => {
    const syncPrefs = () => {
      const nextTheme = readStoredTheme()
      const nextLang = readStoredLang()
      setTheme((current) => (current === nextTheme ? current : nextTheme))
      setLang((current) => (current === nextLang ? current : nextLang))
    }
    window.addEventListener(HERO_PREFS_EVENT, syncPrefs)
    window.addEventListener('storage', syncPrefs)
    return () => {
      window.removeEventListener(HERO_PREFS_EVENT, syncPrefs)
      window.removeEventListener('storage', syncPrefs)
    }
  }, [])

  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS['vi'][key] || key

  const toggleTheme = () => setTheme(t => t === 'dark' ? 'light' : 'dark')

  return (
    <AppContext.Provider value={{ theme, toggleTheme, lang, setLang, t }}>
      {children}
    </AppContext.Provider>
  )
}

export const useApp = () => useContext(AppContext)
